services:
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=maria
      - MYSQL_DATABASE=maria
      - MYSQL_USER=maria
      - MYSQL_PASSWORD=maria
    ports:
      - "3306:3306"

  wordpress:
    build: .
    image: wordpress:latest

    ports:
      - 80:80
    restart: always
    