networks:
  proxy-network:
    external: true

services:
  botspot:
    container_name: botspot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - proxy-network