services:
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=maria
      - MYSQL_DATABASE=maria
      - MYSQL_USER=maria
      - MYSQL_PASSWORD=maria
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql

  wordpress:
    build: .
    image: wordpress:latest
    ports:
      - 80:80
    restart: always
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__Urls=http://*:80
      - ServerOptions__HostName=smtp4dev
      - RelayOptions__Login=example@mail.com
      - RelayOptions__Password=pass


volumes:
  smtp4dev-data:
