import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { Navbar } from './components/Navbar/Navbar';
import { Button } from './components/Button/Button';
import { ReactNode } from 'react';
import ThemeRegistry from './theme/ThemeRegistry';
import { Footer } from './components/Footer/Footer';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeRegistry>
            <Navbar
              navItems={[
                {
                  label: 'Products',
                  children: [
                    { label: 'Option 1' },
                    { label: 'Option 2', children: [{ label: 'Option 2.1' }] },
                  ],
                },
                { label: '3D Scan Service' },
                {
                  label: 'Areas of use',
                  children: [
                    { label: 'Option 1' },
                    { label: 'Option 2', children: [{ label: 'Option 2.1' }] },
                  ],
                },
                { label: 'Learn About 3D Scanning' },
                {
                  label: 'About Us',
                  children: [
                    { label: 'Option 1' },
                    { label: 'Option 2', children: [{ label: 'Option 2.1' }] },
                  ],
                },
              ]}
              cta={<Button variant="secondary">Call to Action</Button>}
            />
            {children}
            <Footer />
          </ThemeRegistry>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
